apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ddns-updater-ingressroute-cert
  namespace: ddns-updater
spec:
  secretName: ddns-updater-cert-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - ddns-updater.maplehillhomestead.com

