apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: default
    ingress.kubernetes.io/force-ssl-redirect: "true"
  name: ddns-updater
spec:
  rules:
    - host: ddns-updater.maplehillhomestead.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ddns-updater
                port:
                  number: 80
  tls:
    - hosts:
        - ddns-updater.maplehillhomestead.com
      secretName: ddns-updater-cert-secret
