service:
  type: ClusterIP
ingress:
  enabled: true
  hosts:
    - host: "portainer2.maplehillhomestead.com"
      paths:
        - path: /
          port: "9000"
  tls:
    - secretName: portainer-cert-secret
      hosts:
        - "portainer2.maplehillhomestead.com"
