service:
  type: ClusterIP
ingress:
  enabled: true
  hosts:
    - host: "portainer.maplehillhomestead.com"
      paths:
        - path: /
          port: "9000"
  tls:
    - secretName: portainer-cert-name
      hosts:
        - "portainer.maplehillhomestead.com"
