apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-ingressroute-cert
  namespace: portainer
spec:
  secretName: portainer-cert-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - portainer.maplehillhomestead.com

